# Generated by Django 4.0.2 on 2022-02-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_ordercomment_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPaymentsIpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_id', models.CharField(max_length=128)),
                ('status', models.SmallIntegerField(choices=[(-2, 'refunded'), (-1, 'timed out'), (0, 'waiting for funds'), (1, 'confirmed reception of funds'), (2, 'queued for nightly payout'), (3, 'paypal pending'), (100, 'payment completed')], default=0)),
                ('currency1', models.CharField(max_length=8)),
                ('currency2', models.CharField(max_length=8)),
                ('amount1', models.DecimalField(decimal_places=18, max_digits=65)),
                ('amount2', models.DecimalField(decimal_places=18, max_digits=65)),
                ('fee', models.DecimalField(decimal_places=18, max_digits=65)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=18, max_digits=65, null=True)),
                ('received_confirms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_coinpayment_ipns',
            },
        ),
        migrations.CreateModel(
            name='PayPalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(max_length=100)),
                ('payer_email', models.CharField(max_length=254)),
                ('payer_id', models.CharField(max_length=13)),
                ('payer_given_name', models.CharField(blank=True, max_length=140, null=True)),
                ('payer_surname', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.CharField(blank=True, max_length=140, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'payment_paypal_orders',
            },
        ),
        migrations.CreateModel(
            name='CoinPaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coinpayments_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=65)),
                ('currency', models.CharField(max_length=5)),
                ('confirms_needed', models.PositiveSmallIntegerField()),
                ('qrcode_url', models.URLField()),
                ('status_url', models.URLField()),
                ('timeout', models.DateTimeField()),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'payment_coinpayment_orders',
            },
        ),
    ]
