# Generated by Django 4.0.2 on 2022-03-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinpaymentsorder',
            old_name='coinpayments_id',
            new_name='txn_id',
        ),
    ]
