# Generated by Django 4.0.2 on 2022-03-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_coinpayments_id_coinpaymentsorder_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpaymentsorder',
            name='currency',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='coinpaymentsorder',
            name='timeout',
            field=models.DateTimeField(blank=True),
        ),
    ]
