# Generated by Django 4.0.2 on 2022-03-17 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_coinpaymentsorder_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinpaymentsorder',
            name='timeout',
        ),
        migrations.AddField(
            model_name='coinpaymentsorder',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 23, 55, 3, 8867, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
