# Generated by Django 4.0.2 on 2022-07-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_total'),
        ('payments', '0005_remove_coinpaymentsorder_timeout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeIpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=128)),
                ('status', models.SmallIntegerField(choices=[(-1, 'canceled'), (0, 'processing'), (1, 'requires_payment_method'), (2, 'requires_confirmation'), (3, 'requires_action'), (4, 'requires_capture'), (5, 'succeeded')], default=0)),
                ('customer_id', models.CharField(max_length=128)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('amount_recieved', models.IntegerField(blank=True, null=True)),
                ('invoice', models.CharField(max_length=255)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.SmallIntegerField(choices=[(0, 'paypal'), (1, 'stripe')], default=None)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-3, 'refunded'), (-2, 'paritally refunded'), (-1, 'cancelled'), (0, 'not paid'), (1, 'awaiting'), (2, 'requires action'), (3, 'captured')], default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
