# Generated by Django 4.0.2 on 2022-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_rename_provider_datas_payment_provider_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider_data',
            field=models.JSONField(),
        ),
    ]
