# Generated by Django 4.0.2 on 2022-07-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_payment_provider_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
