# Generated by Django 4.0.2 on 2022-07-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_paymentsession_alter_payment_status_delete_stripeipn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinPaymentsIpn',
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='status',
            field=models.SmallIntegerField(choices=[(-2, 'error'), (-1, 'canceled'), (0, 'pending'), (1, 'requires more'), (2, 'authorized')], default=0),
        ),
        migrations.DeleteModel(
            name='CoinPaymentsOrder',
        ),
    ]
