# Generated by Django 4.0.2 on 2022-07-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopstripeaccount_charges_enabled_and_more'),
        ('payments', '0013_delete_coinpaymentsipn_alter_paymentsession_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.SmallIntegerField(choices=[(0, 'paypal'), (1, 'stripe')], default=None)),
                ('provider_data', models.JSONField(blank=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'inactive'), (1, 'active')], default=1)),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'db_table': 'payment_provider',
            },
        ),
        migrations.DeleteModel(
            name='PayPalOrder',
        ),
    ]
