# Generated by Django 4.0.2 on 2022-08-08 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_payment_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.UUIDField(default=uuid.UUID('8306ea54-a746-4806-a12b-f55042da6b98'), editable=False, null=True, unique=True),
        ),
    ]
