# Generated by Django 4.0.2 on 2022-08-08 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_payment_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
