# Generated by Django 4.0.2 on 2022-08-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_payment_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ref_id',
        ),
    ]
