# Generated by Django 4.0.2 on 2022-08-08 16:13

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    payment_model = apps.get_model('payments', 'Payment')
    for payment in payment_model.objects.all():
        payment.ref_id = uuid.uuid4()
        payment.save(update_fields=['ref_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_remove_payment_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref_id',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
