# Generated by Django 4.0.2 on 2022-08-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_payment_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
    ]
