# Generated by Django 4.0.2 on 2022-08-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_alter_payment_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
