# Generated by Django 4.0.2 on 2022-08-17 16:47

from django.db import migrations, models


def change_fee(apps, schema_editor):
    payment_model = apps.get_model('payments', 'Payment')
    for payment in payment_model.objects.all():
        payment.fee = payment.fee * 100
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_payment_fee'),
    ]

    operations = [
        migrations.RunPython(change_fee),
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
