# Generated by Django 4.1.1 on 2022-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_alter_payment_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btcpay_data', models.BinaryField()),
            ],
            options={
                'db_table': 'payment_crypto',
            },
        ),
    ]
