# Generated by Django 4.0.2 on 2022-09-06 15:44

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_paymentcrypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcrypto',
            name='btcpay_data',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
