# Generated by Django 4.0.2 on 2022-09-06 19:29

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_alter_paymentcrypto_btcpay_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcrypto',
            name='btcpay_data',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
