# Generated by Django 4.1.1 on 2022-09-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_delete_paymentcrypto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='idempotency_key',
        ),
    ]
