# Generated by Django 4.1.1 on 2022-10-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_paymentprovider_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
