# Generated by Django 4.0.2 on 2022-04-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'free'), (1, 'tier one'), (2, 'tier two')], default=0),
        ),
    ]
