# Generated by Django 4.0.2 on 2022-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_owner_remove_user_subscription_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'free'), (1, 'tier one'), (2, 'tier two')], default=0),
        ),
        migrations.DeleteModel(
            name='ShopOwner',
        ),
    ]
