# Generated by Django 4.0.2 on 2022-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_themeconfiguration_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfiguration',
            name='config_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'unpublished'), (1, 'live')], default=0),
        ),
    ]
