# Generated by Django 4.0.2 on 2022-08-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_themeconfiguration_config_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='theme',
            table='theme',
        ),
        migrations.AlterModelTable(
            name='themeconfiguration',
            table='theme_configuration',
        ),
    ]
