# Generated by Django 4.0.2 on 2022-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_alter_theme_table_alter_themeconfiguration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'private'), (1, 'public')], default=0),
        ),
    ]
