# Generated by Django 4.0.2 on 2022-08-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_code', models.SmallIntegerField()),
                ('iso_2', models.CharField(max_length=2)),
                ('iso_3', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('continent', models.CharField(max_length=255)),
                ('stripe_available', models.BooleanField(default=False)),
                ('paypal_available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
