# Generated by Django 4.0.2 on 2022-04-11 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
