# Generated by Django 4.0.2 on 2022-08-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0002_blacklist_ref_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blacklist',
            table='blacklist',
        ),
    ]
