# Generated by Django 4.1.1 on 2022-11-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklists', '0003_alter_blacklist_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
