# Generated by Django 4.0.2 on 2022-02-21 16:40

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Deleted'), (0, 'Inactive'), (1, 'Active')], default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('domain', models.URLField(blank=True, unique=True)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, on_delete=models.SET(0), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
    ]
