# Generated by Django 4.0.2 on 2022-02-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPayPalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_id', models.CharField(max_length=25)),
                ('permissions_granted', models.BooleanField()),
                ('consent_status', models.BooleanField()),
                ('product_intent_id', models.CharField(max_length=255)),
                ('is_email_confirmed', models.BooleanField()),
                ('account_status', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(-1, 'inactive'), (1, 'active')], default=1)),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'db_table': 'shop_paypal_accounts',
            },
        ),
    ]
