# Generated by Django 4.0.2 on 2022-02-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shoppaypalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCryptoAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitcoin_address', models.CharField(blank=True, max_length=99, null=True)),
                ('ethereum_address', models.CharField(blank=True, max_length=99, null=True)),
                ('litecoin_address', models.CharField(blank=True, max_length=99, null=True)),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'db_table': 'shop_crypto_addresses',
            },
        ),
    ]
