# Generated by Django 4.0.2 on 2022-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopcryptoaddresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppaypalaccount',
            name='email',
            field=models.EmailField(default='hanbotresellers-facilitator@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppaypalaccount',
            name='account_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shoppaypalaccount',
            name='consent_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppaypalaccount',
            name='is_email_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppaypalaccount',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shoppaypalaccount',
            name='permissions_granted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppaypalaccount',
            name='product_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
