# Generated by Django 4.0.2 on 2022-07-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shopstripeaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopstripeaccount',
            options={},
        ),
        migrations.AlterModelTable(
            name='shopstripeaccount',
            table='shop_stripe_accounts',
        ),
    ]
