# Generated by Django 4.0.2 on 2022-07-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopstripeaccount_charges_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppaypalaccount',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopstripeaccount',
            name='shop',
        ),
        migrations.DeleteModel(
            name='ShopCryptoAddresses',
        ),
        migrations.DeleteModel(
            name='ShopPayPalAccount',
        ),
        migrations.DeleteModel(
            name='ShopStripeAccount',
        ),
    ]
