# Generated by Django 4.0.2 on 2022-08-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('shops', '0008_remove_shoppaypalaccount_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
            preserve_default=False,
        ),
    ]
