# Generated by Django 4.0.2 on 2022-08-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shop_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='shop',
        ),
    ]
