# Generated by Django 4.0.2 on 2022-06-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_user_ptr_customer_id_customer_shop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
