# Generated by Django 4.0.2 on 2022-06-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
