# Generated by Django 4.0.2 on 2022-06-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_remove_customer_last_login_remove_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
    ]
