# Generated by Django 4.0.2 on 2022-08-24 14:13

from django.db import migrations


def create_customer(apps, schema_editor):
    order_model = apps.get_model('orders', 'Order')
    user_model = apps.get_model('users', 'User')
    customer_model = apps.get_model('customers', 'Customer')

    for order in order_model.objects.all():
        user_object = user_model.objects.filter(email=order.email)

        if not user_object.exists():
            if order.email is not None:
                user = user_model.objects.create(email=order.email, username=order.email)
                customer = customer_model.objects.create(shop=order.shop, user=user)
                order.customer = customer
                order.save()
        else:
            if order.email is not None:
                customer = customer_model.objects.get_or_create(shop=order.shop, user=user_object.first())
                order.customer = customer
                order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='customernote',
            table='customer_note',
        ),
        migrations.RunPython(create_customer)
    ]
