# Generated by Django 4.1.1 on 2022-10-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='BTC', max_length=3),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
    ]
