# Generated by Django 4.1.1 on 2022-10-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_shop_description'),
        ('payouts', '0002_payout_currency_alter_payout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
            preserve_default=False,
        ),
    ]
