# Generated by Django 4.1.1 on 2022-10-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0004_payout_payout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payout_id',
            field=models.CharField(blank=True, max_length=72),
        ),
    ]
