# Generated by Django 4.1.1 on 2022-10-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0005_alter_payout_payout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
