# Generated by Django 4.1.1 on 2022-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0006_alter_payout_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='payout_id',
        ),
        migrations.AddField(
            model_name='payout',
            name='provider_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
