# Generated by Django 4.0.2 on 2022-05-03 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(max_length=255)),
                ('plan_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('status_update_time', models.DateTimeField(auto_now_add=True)),
                ('payer_email', models.CharField(max_length=254)),
                ('payer_given_name', models.CharField(blank=True, max_length=140, null=True)),
                ('payer_surname', models.CharField(blank=True, max_length=140, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_payment_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_payment_time', models.DateTimeField(auto_now_add=True)),
                ('next_billing_time', models.DateTimeField(auto_now_add=True)),
                ('failed_payments_count', models.IntegerField(default=0)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_paypal',
            },
        ),
    ]
