# Generated by Django 4.0.2 on 2022-05-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalsubscription',
            old_name='payer_email',
            new_name='subscriber_email',
        ),
        migrations.RenameField(
            model_name='paypalsubscription',
            old_name='payer_given_name',
            new_name='subscriber_given_name',
        ),
        migrations.RenameField(
            model_name='paypalsubscription',
            old_name='payer_surname',
            new_name='subscriber_surname',
        ),
        migrations.AddField(
            model_name='paypalsubscription',
            name='subscriber_id',
            field=models.CharField(default='I-76ASD4567S89', max_length=255),
            preserve_default=False,
        ),
    ]
