# Generated by Django 4.0.2 on 2022-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_payer_email_paypalsubscription_subscriber_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalsubscription',
            name='next_billing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
