# Generated by Django 4.0.2 on 2022-05-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_paypalsubscription_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biling_cycle_anchor', models.IntegerField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.BooleanField(default=False)),
                ('current_period_end', models.BooleanField(default=False)),
                ('current_period_start', models.BooleanField(default=False)),
                ('customer', models.CharField(max_length=255)),
                ('default_payment_method', models.CharField(max_length=255)),
                ('ended_at', models.IntegerField()),
                ('latest_invoice', models.CharField(max_length=255)),
                ('start_date', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('stripe_id', models.CharField(max_length=255)),
                ('subscription_tier_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subscriptions_stripe',
            },
        ),
    ]
