# Generated by Django 4.0.2 on 2022-05-06 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0006_stripesubscriptions_ref_id_stripesubscriptions_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeSubscriptions',
            new_name='StripeSubscription',
        ),
    ]
