# Generated by Django 4.0.2 on 2022-05-07 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0007_rename_stripesubscriptions_stripesubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='stripe_id',
            new_name='subscription_id',
        ),
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='subscription_tier_id',
            new_name='subscription_tier',
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='canceled_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='current_period_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='current_period_start',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StripeSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_subtotal', models.PositiveIntegerField(default=0)),
                ('amount_total', models.PositiveIntegerField(default=0)),
                ('customer', models.CharField(max_length=99)),
                ('expires_at', models.DateTimeField()),
                ('payment_intent', models.CharField(max_length=99)),
                ('payment_status', models.SmallIntegerField(choices=[(-1, 'no payment required'), (0, 'unpaid'), (1, 'paid')], default=0)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'paid'), (0, 'open'), (-1, 'expired')], default=0)),
                ('stripe_id', models.CharField(max_length=255)),
                ('subscription', models.CharField(max_length=99)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_stripe_payments',
            },
        ),
    ]
