# Generated by Django 4.0.2 on 2022-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_rename_stripe_id_stripesubscription_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='canceled_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='ended_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionpayment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'paid'), (-1, 'expired'), (0, 'open')], default=0),
        ),
    ]
