# Generated by Django 4.0.2 on 2022-05-07 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0009_alter_stripesubscription_canceled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='biling_cycle_anchor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='current_period_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='current_period_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='default_payment_method',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='latest_invoice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='start_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='subscription_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='subscription_tier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
