# Generated by Django 4.0.2 on 2022-05-07 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0010_alter_stripesubscription_biling_cycle_anchor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscriptionpayment',
            old_name='stripe_id',
            new_name='checkout_id',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionpayment',
            name='amount_subtotal',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionpayment',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionpayment',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionpayment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionpayment',
            name='subscription',
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='amount_captured',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='amount_refunded',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='balance_transaction',
            field=models.CharField(default='pi_98yh9ddw9qn0d0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='created',
            field=models.IntegerField(default=4535345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='disputed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='failure_balance_transaction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='failure_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='failure_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='invoice',
            field=models.CharField(default='in_ds89h98dah9dsad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='outcome_network_status',
            field=models.CharField(default='cool', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='outcome_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='outcome_risk_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='outcome_risk_score',
            field=models.PositiveSmallIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='outcome_seller_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='outcome_type',
            field=models.CharField(default='normal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='payment_method',
            field=models.CharField(default='card', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='payment_method_details_brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='payment_method_details_fingerprint',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='payment_method_details_last4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='payment_method_details_type',
            field=models.CharField(default='qweqwe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='receipt_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='receipt_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='receipt_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripesubscriptionpayment',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionpayment',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionpayment',
            name='payment_intent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionpayment',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionpayment',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'failed'), (0, 'pending'), (1, 'succeeded')], default=0),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
