# Generated by Django 4.0.2 on 2022-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_rename_stripe_id_stripesubscriptionpayment_checkout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscriptionpayment',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
