# Generated by Django 4.0.2 on 2022-08-08 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0012_alter_stripesubscriptionpayment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.SmallIntegerField(choices=[(0, 'paypal'), (1, 'stripe')], default=None)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'canceled'), (0, 'not paid'), (1, 'subscribed')], default=0)),
                ('subscription_tier', models.SmallIntegerField(choices=[(1, 'tier one'), (2, 'tier two'), (3, 'tier three')], null=True)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.SmallIntegerField(choices=[(0, 'paypal'), (1, 'stripe')], default=None)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-3, 'refunded'), (-2, 'paritally refunded'), (-1, 'canceled'), (0, 'not paid'), (1, 'awaiting'), (2, 'requires action'), (3, 'captured')], default=0)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_payment',
            },
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionpayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PayPalSubscription',
        ),
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
        migrations.DeleteModel(
            name='StripeSubscriptionPayment',
        ),
    ]
