# Generated by Django 4.0.2 on 2022-02-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.UUIDField(blank=True, default='9dac1b52-ba4f-4a8d-bb46-316bfe66bce9'),
            preserve_default=False,
        ),
    ]
