# Generated by Django 4.0.2 on 2022-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, db_table='order_items_map', to='orders.OrderItem'),
        ),
    ]
