# Generated by Django 4.0.2 on 2022-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'cancelled'), (0, 'waiting for payment'), (1, 'shipped'), (2, 'delivered')], default=0),
        ),
    ]
