# Generated by Django 4.0.2 on 2022-02-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_currency_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
