# Generated by Django 4.0.2 on 2022-02-26 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomment',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
