# Generated by Django 4.0.2 on 2022-03-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordercomment_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='keys',
            new_name='codes',
        ),
    ]
