# Generated by Django 4.0.2 on 2022-03-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_keys_orderitem_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='codes',
            new_name='keys',
        ),
    ]
