# Generated by Django 4.0.2 on 2022-03-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_codes_orderitem_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='keys',
            new_name='codes',
        ),
    ]
