# Generated by Django 4.0.2 on 2022-04-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_codes_orderitem_purchased_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.SmallIntegerField(blank=True, choices=[(-6, 'chargeback won'), (-5, 'chargeback lost'), (-4, 'chargeback pending'), (-3, 'refunded'), (-2, 'denied'), (-1, 'cancelled'), (0, 'waiting for payment'), (1, 'payment confirmed'), (2, 'pending'), (3, 'complete')], default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='current_status',
            field=models.SmallIntegerField(choices=[(-1, 'cancelled'), (0, 'pending'), (1, 'shipped'), (2, 'delivered')], default=0),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'cancelled'), (0, 'pending'), (1, 'shipped'), (2, 'delivered')], default=0),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(-6, 'chargeback won'), (-5, 'chargeback lost'), (-4, 'chargeback pending'), (-3, 'refunded'), (-2, 'denied'), (-1, 'cancelled'), (0, 'waiting for payment'), (1, 'payment confirmed'), (2, 'pending'), (3, 'complete')], default=0),
        ),
    ]
