# Generated by Django 4.0.2 on 2022-05-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
