# Generated by Django 4.0.2 on 2022-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
