# Generated by Django 4.0.2 on 2022-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.UUIDField(blank=True),
        ),
    ]
