# Generated by Django 4.0.2 on 2022-06-24 03:31

from django.db import migrations, models


def calculate_total(apps, schema_editor):
    order_model = apps.get_model('orders', 'Order')
    for orders in order_model.objects.all():
        items = orders.items.all()
        total = 0

        for item in items:
            total += item.price * item.quantity

        orders.total = total
        orders.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.RunPython(calculate_total)
    ]
