# Generated by Django 4.0.2 on 2022-08-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee',
        ),
    ]
