# Generated by Django 4.0.2 on 2022-08-17 16:25

import django.core.validators
from django.db import migrations, models


def change_price(apps, schema_editor):
    order_model = apps.get_model('orders', 'Order')
    for order in order_model.objects.all():
        order.total = order.total * 100
        order.save()

    order_item_model = apps.get_model('orders', 'OrderItem')
    for order_item in order_item_model.objects.all():
        order_item.price = order_item.price * 100
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_order_fee'),
    ]

    operations = [
        migrations.RunPython(change_price),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0.49), django.core.validators.MaxValueValidator(99999.99)]),
        ),
    ]
