# Generated by Django 4.0.2 on 2022-08-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_total_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='ordercomment',
            table='order_comment',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
        migrations.AlterModelTable(
            name='orderitemstatus',
            table='order_item_status',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
        migrations.AlterModelTable(
            name='orderuserdata',
            table='order_user',
        ),
    ]
