# Generated by Django 4.1.1 on 2022-11-03 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_table_alter_ordercomment_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
