# Generated by Django 4.0.2 on 2022-02-21 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shopcryptoaddresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'digital'), (1, 'physical')], default=1)),
                ('status', models.SmallIntegerField(choices=[(-2, 'out of stock'), (-1, 'deleted'), (0, 'unlisted'), (1, 'listed')], default=0)),
                ('slug', models.SlugField(blank=True)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.49), django.core.validators.MaxValueValidator(99999.99)])),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
