# Generated by Django 4.0.2 on 2022-02-22 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=99)),
                ('status', models.SmallIntegerField(blank=True, choices=[(-1, 'deleted'), (0, 'listed'), (1, 'purchased')], default=0)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'products_digital',
            },
        ),
    ]
