# Generated by Django 4.0.2 on 2022-02-22 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_digitalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
