# Generated by Django 4.0.2 on 2022-08-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='digitalproduct',
            table='product_digital',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
