# Generated by Django 4.0.2 on 2022-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_digitalproduct_table_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum_order_quantiy',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quanity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
