# Generated by Django 4.0.2 on 2022-09-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_maximum_order_quantiy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maximum_order_quantiy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quanity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
