# Generated by Django 4.0.2 on 2022-09-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_maximum_order_quantiy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maximum_order_quantiy',
            field=models.PositiveIntegerField(default=2147483647),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quanity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
