# Generated by Django 4.0.2 on 2022-09-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_maximum_order_quantiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maximum_order_quantiy',
            new_name='max_order_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='minimum_order_quanity',
            new_name='min_order_quantity',
        ),
    ]
