# Generated by Django 4.1.1 on 2022-11-03 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_maximum_order_quantiy_product_max_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
